--- #YAML:1.0
name:                Template-Toolkit
version:             2.19_01
abstract:            comprehensive template processing system
license:             perl
author:              
    - Andy Wardley <abw@wardley.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    AppConfig:                     1.56
    File::Spec:                    0.8
    File::Temp:                    0.12
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
